### ISSUE TITLE
General concept and understanding questions by Nirav

### ISSUE THREAD

**Issue by niravassar** [grails/grails-testing-support#3]
- in general what is the purpose of the plugin - what i gather is its simple and more efficient way so developers dont have to import annotation like @Mock and @TestFor
- in DomainUnitTest, we dont have to mock the domain class. However, in the usage of DataTest we have to use mockDomain (as it was used in 2.x). Why would we go this route. 
- with ServiceUnitTest, what is the difference between using it vs @TestFor. is it essentially the same or does it have other traits to use. 
- is doWithSpring in unit test feature contain in the grails-testing-support jar? i thought it was already present before
- I am not familiar with how the grails scripts run and operate such as `create-controller` and `create-domain-class`. Are they scripts in the installation, or have they changed? Where are these checked in and how do we add to development.

**Comment by jeffbrown** [comment]
> - in general what is the purpose of the plugin - what i gather is its simple and more efficient way so developers dont have to import annotation like @Mock and @TestFor

Not having to import `@Mock` and `@TestFor` isn't really one of the benefits.  Those imports are just replaced with different imports.

A primary motivator for the new testing framework is to provide a trait based solution.  Using traits is better than our current AST Transformation system for several reasons including the following:

- We get to eliminate a bunch of complex AST Transformation code
- Traits are more IDE friendly so developers get better auto-completion, click through navigation into where properties are defined, etc.
- Less magic.  Developers can know what properties and methods are available just by looking at the trait. 


> - in DomainUnitTest, we dont have to mock the domain class. However, in the usage of DataTest we have to use mockDomain (as it was used in 2.x). Why would we go this route. 

`DomainUnitTest` is used when you want to write a test for a particular domain class.  The type is parameterized so you can have something like `... implements DomainUnitTest<Person>`.  `DataTest` is for a test that isn't necessarily for a particular class, but the test exercises code that relies on GORM.  For example, testing a controller which might be using GORM.  That might involve numerous domain classes so with `DataTest` you get to call `mockDomain` or `mockDomains` and mock as many domain classes as you like.  One could ignore `DomainUnitTest` and get all of the corresponding behavior by using just `DataTest`.  The other way around is not true.  That said, `DomainUnitTest` is a convenience for tests that are specifically focused on a particular domain class.

> - with ServiceUnitTest, what is the difference between using it vs @TestFor. is it essentially the same or does it have other traits to use. 

See answer to the first question above.

> - is doWithSpring in unit test feature contain in the grails-testing-support jar? i thought it was already present before

It was present before.  The new testing library supports it as well.  I think we should change the implementation so `doWithSpring` is a method that returns a `Closure` instead of it being a `Closure` property.

> - I am not familiar with how the grails scripts run and operate such as `create-controller` and `create-domain-class`. Are they scripts in the installation, or have they changed? Where are these checked in and how do we add to development. 

This is all in the profiles.  There is a little bit to it and I know you are all set now and getting setup with a local dev env to work with those.  Once we get all of that up and running, if you still have questions just let me know.

Thanks!
